version: "3"
services:
  db:
    image: mongo:4.2
    container_name: bkman-db
    hostname: db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=bkman
  mongo-express:
    image: mongo-express:0.54
    container_name: bkman-mongoexpress
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_SERVER: db
  backend:
    image: node:16.13.2-alpine
    container_name: bkman-backend
    hostname: backend
    command: sh -c "cd /app && yarn && yarn start:debug"
    ports:
      - 3001:3001
      - 9230:9230
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - "db"
  frontend:
    image: node:16.13.2-alpine
    container_name: bkman-frontend
    hostname: frontend
    command: sh -c "cd /app && yarn && yarn dev"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - "backend"